# Generated by Django 4.0.2 on 2022-02-15 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('body', models.TextField()),
                ('uptime', models.DateTimeField(auto_now=True)),
                ('creation', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-uptime'],
            },
        ),
    ]
